/*
* IMPORTANT: This trigger was automatically generated by Sitetracker.
*
* This trigger is required for functionality to work properly and should not be modified or removed.
* If you would like to implement custom trigger logic for this object, you should create a
* second trigger and add your logic there.
*/
trigger SiteDevelopmentATTTrigger on Site_Development_AT_T__c (after delete, after insert, after undelete, after update, before delete, before insert, before update){
    strk.StTriggerFactory.createAndExecuteHandler(UnitiSiteDevelopmentATTTriggerHandler.class, 'Site_Development_AT_T__c');
}