/*************************************************************************************************
* SITETRACKER, INC. (“Sitetracker”) CONFIDENTIAL
* Unpublished Copyright (c) 2013-2023 SITETRACKER, INC., All Rights Reserved.
*
* NOTICE: All information contained herein is, and remains the property of Sitetracker.
* The intellectual and technical concepts contained herein are proprietary to Sitetracker and
* may be covered by U.S. and Foreign Patents, patents in process, and are protected by trade
* secret or copyright law.
*
* Dissemination of this information or reproduction of this material is strictly forbidden unless
* prior written permission is obtained from Sitetracker. Access to the source code contained
* herein is hereby forbidden to anyone except current Sitetracker employees, managers or
* contractors who have executed Confidentiality and Non-disclosure agreements explicitly
* covering such access.
*
* The copyright notice above does not evidence any actual or intended publication or disclosure
* of this source code, which includes information that is confidential and/or proprietary, and
* is a trade secret, of Sitetracker.
*
* @description Uniti_Constants
*
*
* @author <A HREF="mailto:vsaran@sitetracker.com">Vartika Saran</A>
*
***************************************************************************************************/
global without sharing class Uniti_Constants{
    global static final String PROJECT_TEMP_CATEGORY_TOWERS = 'Towers';
    global static final String PROJECT_AGREEMENT_ABM = 'ABM';
    global static final String PROJECT_CATEGORY_DEVELOPMENT = 'Development';
    global static final String PROJECT_ACCEPTANCE_OBJECT_TYPE = String.valueOf(Project_Acceptance__c.SObjectType);
    global static final String ST_APPROVAL_PROCESS_TEMPLATE = String.valueOf(strk__Approval_Process_Template__c.SObjectType);
}